### PR TITLE
Avoid hardcoding ipaddress6 default

### LINKED ISSUE #15: Impossible to set ipaddress6 fact
## Describe the Bug

It is not possible to set the `ipaddress6` fact to any other value than `FE80:0000:0000:0000:AAAA:AAAA:AAAA`.

## Expected Behavior

The `ipaddress6` fact should behave like other facts.

## Steps to Reproduce

Create a class `manifests/init.pp`:

```puppet
class puppet_ipaddress6_test {
  file { '/foo':
    content => $facts['ipaddress6'],
  }
}
```

And a spec test `spec/classes/init_spec.rb`:

```ruby
require 'puppetlabs_spec_helper/module_spec_helper'

describe 'puppet_ipaddress6_test', :type => :class do
    let (:node) { 'server.example.org' }
    let (:facts) do {
        'ipaddress6' => '2001:db8::1',
    } end
    it {
        is_expected.to contain_file('/foo').
            with_content(/^2001:db8::1$/)
    }
end
```

And a `Rakefile`:

```ruby
require 'puppetlabs_spec_helper/rake_tasks'
```

Then run the spec test:

```sh
rake spec
```

It will fail with the following error:
```
  1) puppet_ipaddress6_test is expected to contain File[/foo] with content =~ /^2001:db8::1$/
     Failure/Error:
       is_expected.to contain_file('/foo').
           with_content(/^2001:db8::1$/)
     
       expected that the catalogue would contain File[/foo] with content set to /^2001:db8::1$/ but it is set to "FE80:0000:0000:0000:AAAA:AAAA:AAAA"
     # ./spec/classes/init_spec.rb:9:in `block (2 levels) in <top (required)>'
```

## Environment

* rspec-puppet version 2.10.0
* [Gemfile](https://github.com/puppetlabs/rspec-puppet/files/7452884/Gemfile.txt)
* [Gemfile.lock](https://github.com/puppetlabs/rspec-puppet/files/7452882/Gemfile.lock.txt)

## Additional Context

The hard-coded `ipaddress6` fact was introduced in [(#771) Set a default dummy ipaddress6 fact](https://github.com/rodjek/rspec-puppet/pull/772).

### PR DESCRIPTION
**Pull request by ekohl**
## Summary

In 4ef2f3643eaab642d2f24ffda6a507699d9ae0a8 this was added as a workaround, but in 48c56051047667ff6f7f3915d7597e2da669e26d a custom Facter implementation was added. This avoids any calls to the real Facter and doesn't suffer from the issue where it was attempting to load Windows gems on Linux.

## Additional Context

- [x] Root cause and the steps to reproduce.
- [x] Thought process behind the implementation.

## Related Issues (if any)

Fixes #15

## Checklist

- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified.

### CODE REVIEW

**Comment by olavmrk** [comment]
Thank you for looking into this!

I tested this change by pulling in your branch in the test project I created when testing #15:

```patch
diff --git a/Gemfile b/Gemfile
index 284dc42..710e8bb 100644
--- a/Gemfile
+++ b/Gemfile
@@ -1,2 +1,3 @@
 source 'https://rubygems.org'
 gem 'puppetlabs_spec_helper'
+gem 'rspec-puppet', git: 'https://github.com/ekohl/rspec-puppet.git', branch: 'avoid-hardcoding-ipaddress6'
```

Unfortunately it does not appear to make any difference.
The `ipaddress6` fact still has the same hard-coded value:

<details><summary>Show log</summary>

```
$ bundle exec rake spec
I, [2023-07-14T12:17:43.807454 #268318]  INFO -- : Creating symlink from spec/fixtures/modules/puppet_ipaddress6_test to /home/olavmo/puppet_ipaddress6_test
/usr/bin/ruby3.0 -I/home/olavmo/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib:/home/olavmo/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-support-3.12.1/lib /home/olavmo/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb
F

Failures:

  1) puppet_ipaddress6_test is expected to contain File[/foo] with content =~ /^2001:db8::1$/
     Failure/Error:
       is_expected.to contain_file('/foo').
           with_content(/^2001:db8::1$/)
     
       expected that the catalogue would contain File[/foo] with content set to /^2001:db8::1$/ but it is set to "FE80:0000:0000:0000:AAAA:AAAA:AAAA"
     # ./spec/classes/init_spec.rb:9:in `block (2 levels) in <top (required)>'

Finished in 0.15624 seconds (files took 0.63642 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/classes/init_spec.rb:8 # puppet_ipaddress6_test is expected to contain File[/foo] with content =~ /^2001:db8::1$/

/usr/bin/ruby3.0 -I/home/olavmo/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib:/home/olavmo/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-support-3.12.1/lib /home/olavmo/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb failed
```

</details>

I will be away for a while, so I won't be able to do further testing in a while, but I have attached a ZIP-file with my test project:

* [puppet_ipaddress6_test.zip](https://github.com/puppetlabs/rspec-puppet/files/12049360/puppet_ipaddress6_test.zip)

See the output below for an example of how I tested this:

<details><summary>Running the test from the ZIP file</summary>

```console
$ cd /tmp/
$ mkdir puppet_ipaddress6_test
$ cd puppet_ipaddress6_test/
$ wget https://github.com/puppetlabs/rspec-puppet/files/12049360/puppet_ipaddress6_test.zip
[...]
2023-07-14 12:20:09 (500 KB/s) - ‘puppet_ipaddress6_test.zip’ saved [2269/2269]
$ unzip puppet_ipaddress6_test.zip
Archive:  puppet_ipaddress6_test.zip
4c946aace4e67bcbae9c71b772315d17417fd1b3
 extracting: .gitignore              
  inflating: Gemfile                 
  inflating: Gemfile.lock            
 extracting: Rakefile                
   creating: manifests/
  inflating: manifests/init.pp       
   creating: spec/
   creating: spec/classes/
  inflating: spec/classes/init_spec.rb  
$ bundle config set --local path 'vendor/bundle'
$ bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching https://github.com/ekohl/rspec-puppet.git
[...]
Bundle complete! 2 Gemfile dependencies, 28 gems now installed.
Bundled gems are installed into `./vendor/bundle`
$ bundle exec rake spec
I, [2023-07-14T12:20:39.756322 #268777]  INFO -- : Creating symlink from spec/fixtures/modules/puppet_ipaddress6_test to /tmp/puppet_ipaddress6_test
/usr/bin/ruby3.0 -I/tmp/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib:/tmp/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-support-3.12.1/lib /tmp/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb
F

Failures:

  1) puppet_ipaddress6_test is expected to contain File[/foo] with content =~ /^2001:db8::1$/
     Failure/Error:
       is_expected.to contain_file('/foo').
           with_content(/^2001:db8::1$/)
     
       expected that the catalogue would contain File[/foo] with content set to /^2001:db8::1$/ but it is set to "FE80:0000:0000:0000:AAAA:AAAA:AAAA"
     # ./spec/classes/init_spec.rb:9:in `block (2 levels) in <top (required)>'

Finished in 0.18995 seconds (files took 0.60521 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/classes/init_spec.rb:8 # puppet_ipaddress6_test is expected to contain File[/foo] with content =~ /^2001:db8::1$/

/usr/bin/ruby3.0 -I/tmp/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/lib:/tmp/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-support-3.12.1/lib /tmp/puppet_ipaddress6_test/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.12.2/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb failed
```

</details>

**Comment by ekohl** [comment]
@olavmrk to benefit from this you will need to set up [rspec-puppet-facts](https://github.com/voxpupuli/rspec-puppet-facts). You need a proper metadata.json for `on_supported_os`, but then you can run:
```ruby
require 'puppetlabs_spec_helper/module_spec_helper'                                        
require 'rspec-puppet-facts'
  
RSpec.configure do |c|                                                                     
  c.facter_implementation = :rspec                                                         
end
  
include RspecPuppetFacts                                                                   
  
describe 'puppet_ipaddress6_test' do                                                       
  on_supported_os.each do |os, os_facts|                                                   
    context "on #{os}" do
      let(:facts) { os_facts.merge(ipaddress6: '2001:db8::1') }                            
      let(:node) { 'server.example.org' }                                                  
    
      it { is_expected.to contain_file('/foo').with_content('2001:db8::1') }               
    end                                                                                    
  end
end
```

File: lib/rspec-puppet/support.rb [hunk 1]
```diff
@@ -242,9 +242,17 @@ def facts_hash(node)
         'fqdn' => node,
         'domain' => node.split('.', 2).last,
         'clientcert' => node,
```
Comment (ekohl) [inline lib/rspec-puppet/support.rb:244]: Can I just say I hate the `Style/TrailingCommaInHashLiteral` setting that's in this project? It creates bigger diffs than needed.

**Review by bastelfreak — APPROVED** [review]

File: lib/rspec-puppet/support.rb (hunk 1 above)
Comment (LukasAud) [reply lib/rspec-puppet/support.rb]: Noted. Although if its a rubocop setting, then its probably a standard in all our modules and tools by now.

**Comment by LukasAud** [comment]
The PR looks good, although this has shed some light on for me on the fact that this tool appears to still be using legacy facts.

**Review by LukasAud — APPROVED** [review]
LGTM
